name: CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            non_experimental: ${{ steps.filter.outputs.non_experimental }}
        steps:
            - uses: actions/checkout@v4
            - id: filter
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      experimental:
                        - 'experimental/**'
                      non_experimental:
                        - '**'
                        - '!experimental/**'

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'
            - run: npm ci
            - run: npm run lint
            - run: npm run format -- --check && git diff --exit-code

    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npx markdownlint-cli docs/**/*.md

    build:
        needs: changes
        if: needs.changes.outputs.non_experimental == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'
            - run: npm ci
            - run: npm run build

    test:
        needs: changes
        if: needs.changes.outputs.non_experimental == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'
            - run: npm ci
            - run: npm test
